name: Daily TickTick Summary

on:
  schedule:
    - cron: '0 14 * * 1-5'
  workflow_dispatch:

jobs:
  habit-summary:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Post TickTick habit summary to Slack
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          TICKTICK_COOKIE: ${{ secrets.TICKTICK_COOKIE }}
        run: python scripts/habit_checkins_to_slack.py
